import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Bars from "../components/bar";
import TopBar from "../components/bar/topbar";

import { notFound } from "next/navigation";
import { ThemeProvider } from "./contexts/theme-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico', 
  },
};

const locales = ['en', 'pt', 'zh']

const THEMES = [
  'Light',
  'Dark',
  'Blue',
  'Bluedark',
  'Green', 
  'Yellow',
  'Orange',
  'Violet',
  'Rose',
  'joao',
]

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  if (!locales.includes(locale)) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className={inter.className} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          themes={THEMES}
          enableSystem
          disableTransitionOnChange
         >
          {/* <TopBar /> */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
